export const ARCHITECTURE_SYSTEM_PROMPT = `You are a principal software engineer conducting an architecture review. You have deep expertise in software design patterns, clean code principles, system design, and large-scale software architecture. You focus on structural improvements with high impact.

## Your Review Areas

### Code Organization & Separation of Concerns
- Is business logic separated from infrastructure?
- Are there clear boundaries between layers (routes, services, data)?
- Is the codebase navigable for new developers?

### Design Patterns
Patterns to look for:
- Repository Pattern for data access
- Factory Pattern for object creation
- Strategy Pattern for interchangeable algorithms
- Middleware Pattern for cross-cutting concerns
- Module Pattern for encapsulation

Anti-patterns to flag:
- God Objects (classes that do too much)
- Spaghetti Code (tangled control flow)
- Magic Numbers/Strings
- Copy-Paste Programming
- Callback Hell
- Tight Coupling

### Error Handling Strategy
- Is there a consistent error handling approach?
- Are errors handled at appropriate levels?
- Is there proper error propagation?
- Are errors logged with sufficient context?

### Input Validation Architecture
- Is validation centralized or scattered?
- Are there validation schemas/middleware?
- Is validation happening at the right layer?

### Dependency Management
- Is dependency injection used?
- Are dependencies explicit or hidden?
- Can components be tested in isolation?
- Are there circular dependencies?

### Database Access Patterns
- Is database access abstracted?
- Are queries parameterized?
- Is connection pooling used?
- Are transactions handled properly?

### API Design Consistency
- Are endpoints RESTful and consistent?
- Is error response format standardized?
- Are HTTP status codes used correctly?
- Is versioning considered?

### Configuration Management
- Are configs externalized?
- Are secrets handled securely?
- Is there environment-specific config?

### Logging & Observability
- Is logging consistent and structured?
- Are appropriate log levels used?
- Is there enough context for debugging?

### Testing Considerations
- Is the code testable?
- Are dependencies mockable?
- Are there clear units to test?

## Your Guiding Principles

### SOLID Principles
- **S**ingle Responsibility: One reason to change
- **O**pen/Closed: Open for extension, closed for modification
- **L**iskov Substitution: Subtypes must be substitutable
- **I**nterface Segregation: Many specific interfaces over one general
- **D**ependency Inversion: Depend on abstractions

### Core Principles
- **DRY**: Don't Repeat Yourself
- **KISS**: Keep It Simple, Stupid
- **YAGNI**: You Aren't Gonna Need It
- **Fail Fast**: Detect errors early
- **Defense in Depth**: Multiple layers of protection

## Your Rules

1. **Prioritize by impact**: High-impact suggestions first—what gives the most value for effort?
2. **Show the code**: Every suggestion MUST include substantial before/after code examples (at least 5-10 lines each) that clearly demonstrate the improvement
3. **Cross-reference bugs**: Reference specific security bugs that your suggestion would PREVENT
4. **Be pragmatic**: Suggest incremental improvements, not complete rewrites
5. **Consider effort**: Note how long each suggestion would take to implement
6. **Root causes**: Address WHY bugs happened, not just the bugs themselves
7. **Real-world impact**: Explain how each architectural problem affects development velocity, bug frequency, and maintainability in practical terms
8. **Be thorough**: Provide detailed descriptions of at least 3-4 sentences per suggestion, explaining the problem, its impact, and why your solution is the right approach
9. **No length restrictions**: Provide as much detail as needed. More thorough analysis is preferred

You are the LAST specialist to analyze the code. You have access to:
- All security bugs found by the Security Specialist
- Documentation generated by the Technical Writer
- The full codebase

Your job is to identify STRUCTURAL improvements that would prevent entire CATEGORIES of bugs, not just individual issues.

You must ALWAYS respond with valid JSON only. No markdown, no code fences, no explanation, no preamble. Raw JSON only.`;

export function buildArchitecturePrompt(files, bugs, documentation, coordinatorPlan) {
  const projectType = coordinatorPlan?.projectType || 'software project';
  const architectureInstructions = coordinatorPlan?.agentFocusAreas?.architecture ||
    'Perform a comprehensive architecture review focusing on maintainability and security.';

  // Format files
  const filesContent = files.map(f => {
    return `### File: ${f.path} (${f.language})
\`\`\`${f.language}
${f.content}
\`\`\``;
  }).join('\n\n');

  // Format bugs with IDs for cross-referencing
  const bugsContent = bugs.length > 0
    ? bugs.map(b => {
        return `- **${b.id}** [${b.severity?.toUpperCase()}] ${b.title}
    File: ${b.file}, Line: ${b.line}
    Type: ${b.type}
    Issue: ${b.description}`;
      }).join('\n')
    : 'No security issues were found.';

  // Truncate documentation
  const docPreview = documentation && documentation.length > 300
    ? documentation.substring(0, 300) + '...'
    : documentation || 'No documentation was generated.';

  // Group bugs by type for pattern analysis
  const bugsByType = {};
  bugs.forEach(b => {
    bugsByType[b.type] = (bugsByType[b.type] || 0) + 1;
  });
  const bugPatterns = Object.entries(bugsByType)
    .map(([type, count]) => `${type}: ${count}`)
    .join(', ') || 'None';

  return `Conduct an architecture review of this codebase with full context from previous specialist agents.

## Project Information
- **Project Type**: ${projectType}
- **Files to Review**: ${files.length}
- **Security Issues Found**: ${bugs.length}
- **Bug Patterns**: ${bugPatterns}

## Coordinator Instructions
${architectureInstructions}

## Security Bugs Found (Reference these by ID in your suggestions)
${bugsContent}

## Documentation Generated (Preview)
${docPreview}

## Source Code Files
${filesContent}

## Your Task

Analyze the architecture and suggest structural improvements that:
1. Address ROOT CAUSES of the security bugs listed above
2. Prevent entire CATEGORIES of bugs from occurring
3. Improve maintainability and code organization
4. Apply appropriate design patterns

Respond with this EXACT JSON structure:

{
  "suggestions": [
    {
      "id": "arch_001",
      "title": "Short descriptive title",
      "description": "Detailed explanation of the structural problem and why it matters. Explain how this architectural issue led to specific bugs.",
      "impact": "high|medium|low",
      "category": "security|maintainability|performance|testing|error-handling|patterns",
      "affectedFiles": ["path/to/file1.js", "path/to/file2.js"],
      "beforeCode": "// Current problematic code pattern\\nconst result = db.query('SELECT * FROM users WHERE id = ' + id);",
      "afterCode": "// Improved code with proper architecture\\nconst result = await userRepository.findById(id);",
      "preventsBugIds": ["sec_001", "sec_002"],
      "estimatedEffort": "15 minutes|1 hour|half day|1 day"
    }
  ],
  "overallAssessment": "2-3 sentence architectural assessment summarizing the codebase structure, main strengths, and critical weaknesses",
  "architectureScore": 70,
  "biggestRisk": "The single most important structural issue that should be addressed first",
  "quickWins": ["arch_001", "arch_003"]
}

Guidelines for your suggestions:
- **HIGH impact**: Fixes that prevent multiple bugs or affect core architecture
- **MEDIUM impact**: Improvements to significant subsystems
- **LOW impact**: Nice-to-have improvements, minor cleanups

For "preventsBugIds": List the bug IDs (like "sec_001") that this architectural change would prevent. This is CRITICAL for showing how your suggestions connect to real bugs.

For "quickWins": List suggestion IDs that can be implemented in under 1 hour.

Architecture Score Guidelines:
- 90-100: Excellent architecture, well-organized, proper patterns
- 70-89: Good structure, some improvements needed
- 50-69: Adequate, notable structural issues
- 30-49: Poor architecture, significant refactoring needed
- 0-29: Critical architectural problems, high technical debt

Respond with valid JSON only. No markdown, no code fences.`;
}

export function buildPatternAnalysisPrompt(files) {
  const filesContent = files.map(f => {
    return `### ${f.path} (${f.language})
\`\`\`${f.language}
${f.content}
\`\`\``;
  }).join('\n\n');

  return `Analyze the design patterns present in this codebase.

## Source Code
${filesContent}

## Your Task

Identify which design patterns are present, which are missing but would be beneficial, and which anti-patterns exist.

Respond with this EXACT JSON structure:

{
  "patternsPresent": [
    {
      "pattern": "Pattern Name (e.g., MVC, Repository, Factory)",
      "location": "Where it's implemented",
      "quality": "well-implemented|partial|poor"
    }
  ],
  "patternsMissing": [
    {
      "pattern": "Pattern Name",
      "whereNeeded": "Where this pattern should be applied",
      "benefit": "What problem it would solve"
    }
  ],
  "antiPatterns": [
    {
      "antiPattern": "Anti-pattern name (e.g., God Object, Spaghetti Code)",
      "location": "file.js or specific area",
      "severity": "high|medium|low",
      "description": "Why this is problematic"
    }
  ]
}

Common patterns to look for:
- MVC/MVP/MVVM (Model-View-Controller variants)
- Repository Pattern (data access abstraction)
- Factory Pattern (object creation)
- Singleton Pattern (single instance)
- Observer Pattern (event handling)
- Middleware Pattern (request pipeline)
- Strategy Pattern (interchangeable algorithms)
- Dependency Injection (explicit dependencies)
- Module Pattern (encapsulation)

Common anti-patterns to flag:
- God Object (class/file doing too much)
- Spaghetti Code (tangled, hard to follow)
- Copy-Paste Programming (duplicated code)
- Magic Numbers/Strings (hardcoded values)
- Callback Hell (deeply nested callbacks)
- Tight Coupling (components too dependent)
- Premature Optimization
- Golden Hammer (using same solution for everything)

Respond with valid JSON only. No markdown, no code fences.`;
}
